apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-playground
  labels:
    app: kubernetes-playground
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: persistence
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      name: pod
      labels:
        app: kubernetes-playground
        type: persistence
    spec:
      containers:
        - name: redis
          image: redis
