apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubernetes-playground
  labels:
    app: kubernetes-playground
    type: backend
spec:
  template:
    metadata:
      name: pod
      labels:
        app: kubernetes-playground
        type: persistence
    spec:
      containers:
        - name: redis
          image: redis
  replicas: 2
  selector:
    matchLabels:
      type: persistence