apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo
spec:
  containers:
    - name: result-pod
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80